@echo off
echo Starting MongoDB and Development Server...
echo.
echo Starting MongoDB in background...
start /B "MongoDB" "C:\Program Files\MongoDB\Server\8.0\bin\mongod.exe" --dbpath "./mongodb-data" --port 27017

echo Waiting for MongoDB to start...
timeout /t 3 /nobreak >nul

echo Starting Development Server...
npm run dev
